import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { ChevronLeft, Download, Share2, Lightbulb, Heart, TrendingUp, Zap, Target, Brain, ExternalLink, AlertTriangle, ChevronDown, ChevronUp, Activity, BarChart3, Star } from "lucide-react";
import { RiskProfile } from "@shared/schema";
import type { PersonalizedRecommendations } from "../utils/adaptiveSuggestions";
import { RiskRadarChart } from "./RiskRadarChart";

interface ResultsPageProps {
  profile: RiskProfile;
  adaptiveRecommendations: PersonalizedRecommendations | null;
  eriResults: { eriScore: number; riskLevel: string; subScores: any } | null;
  onStartOver: () => void;
}

export function ResultsPage({ profile, adaptiveRecommendations, eriResults, onStartOver }: ResultsPageProps) {
  const [narrativeOpen, setNarrativeOpen] = useState(false);
  const [suggestionsOpen, setSuggestionsOpen] = useState(true); // Open by default
  const [personalizedOpen, setPersonalizedOpen] = useState(true); // Open by default
  const [analyticsOpen, setAnalyticsOpen] = useState(false);

  const handleExport = () => {
    // Create a simple text export of the results
    const results = `
Mental Health Risk Profile Results
=================================

Profile: ${profile.name} ${profile.emoji}

Emotional Narrative:
"${profile.narrative}"

Key Philosophy:
"${profile.philosophy}"

Detailed Profile:
${profile.narrative}

Recommended Actions:
Immediate: ${profile.suggestions.immediate}
Medium-term: ${profile.suggestions.mediumTerm}
Mindset: ${profile.suggestions.mindset}

Who Else Went Through This:
${profile.whoElseWentThroughThis}

Celebrity Parallel: ${profile.celebrityParallel}

---
This assessment is for informational purposes only and should not replace professional mental health care.
Generated by Mental Health Risk Profiling Tool
    `.trim();

    const blob = new Blob([results], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mental-health-profile-${profile.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: 'Mental Health Risk Profile',
        text: `I completed a mental health assessment and my profile is: ${profile.name}`,
        url: window.location.href
      });
    } else {
      // Fallback to clipboard
      navigator.clipboard.writeText(
        `I completed a mental health assessment and my profile is: ${profile.name} - ${window.location.href}`
      );
      console.log('Results copied to clipboard');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary/5 to-accent/10 p-4">
      <div className="container mx-auto max-w-4xl py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold mb-2">Your Mental Health Profile</h1>
          <p className="text-muted-foreground">
            Based on your responses, here's your personalized risk profile and recommendations
          </p>
        </div>

        {/* Summary Card */}
        <Card className="mb-6">
          <CardHeader className="text-center">
            <div className="text-6xl mb-4">{profile.emoji}</div>
            <CardTitle className="text-2xl mb-2">{profile.name}</CardTitle>
            <CardDescription className="text-lg max-w-2xl mx-auto">
              {profile.narrative}
            </CardDescription>
            {eriResults && (
              <div className="flex justify-center gap-4 mt-4">
                <Badge variant={eriResults.riskLevel === 'Low' ? 'default' : eriResults.riskLevel === 'Medium' ? 'secondary' : 'destructive'} className="text-sm">
                  ERI Score: {eriResults.eriScore}/100 ({eriResults.riskLevel})
                </Badge>
              </div>
            )}
          </CardHeader>
        </Card>

        {/* Progressive Disclosure Sections */}
        <div className="space-y-4">
          
          {/* Personalized Action Plan */}
          {adaptiveRecommendations && (
            <Collapsible open={personalizedOpen} onOpenChange={setPersonalizedOpen}>
              <Card>
                <CollapsibleTrigger asChild>
                  <CardHeader className="cursor-pointer hover-elevate" data-testid="collapsible-personalized-action-plan">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <Target className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">Your Personalized Action Plan</CardTitle>
                      </div>
                      {personalizedOpen ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
                    </div>
                    <CardDescription>
                      Custom recommendations based on your profile and risk factors
                    </CardDescription>
                  </CardHeader>
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <CardContent className="pt-0">
                    {eriResults && eriResults.eriScore >= 70 && (
                      <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4 mb-6">
                        <div className="flex items-start gap-3">
                          <AlertTriangle className="h-5 w-5 text-destructive mt-0.5" />
                          <div>
                            <h3 className="font-semibold text-destructive mb-2">Immediate Support Recommended</h3>
                            <p className="text-sm text-muted-foreground mb-3">
                              Based on your responses, consider reaching out for professional support.
                            </p>
                            <div className="flex flex-wrap gap-2">
                              <Button size="sm" variant="destructive" data-testid="button-crisis-hotline">
                                Crisis Hotline: 988
                              </Button>
                              <Button size="sm" variant="outline" data-testid="button-find-therapist">
                                Find a Therapist
                              </Button>
                            </div>
                          </div>
                        </div>
                      </div>
                    )}

                    <div className="space-y-4">
                      {adaptiveRecommendations.primarySuggestions.map((suggestion, index) => (
                        <div key={index} className="border rounded-lg p-4">
                          <div className="flex items-start justify-between mb-2">
                            <h4 className="font-semibold">{suggestion.text}</h4>
                            <Badge variant="outline">Priority {suggestion.priority}</Badge>
                          </div>
                          <p className="text-sm mb-3">{suggestion.reasoning}</p>
                          <div className="flex items-center gap-2 text-xs text-muted-foreground">
                            <span>Category: {suggestion.category}</span>
                          </div>
                        </div>
                      ))}
                    </div>

                    {adaptiveRecommendations.additionalResources.length > 0 && (
                      <div className="mt-6">
                        <h4 className="font-semibold mb-3 flex items-center gap-2">
                          <ExternalLink className="h-4 w-4" />
                          Recommended Resources
                        </h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                          {adaptiveRecommendations.additionalResources.map((resource, index) => (
                            <div key={index} className="border rounded-lg p-3 hover-elevate">
                              <div className="flex items-start justify-between mb-2">
                                <h5 className="font-medium text-sm">{resource.title}</h5>
                                <Badge variant="secondary" className="text-xs">{resource.type}</Badge>
                              </div>
                              <p className="text-xs text-muted-foreground mb-2">{resource.description}</p>
                              <div className="flex items-center gap-2 text-xs text-muted-foreground">
                                <span>Evidence: {resource.evidence}</span>
                                <Separator orientation="vertical" className="h-3" />
                                <span>Time: {resource.timeCommitment}</span>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </CardContent>
                </CollapsibleContent>
              </Card>
            </Collapsible>
          )}

          {/* Profile-Based Suggestions */}
          <Collapsible open={suggestionsOpen} onOpenChange={setSuggestionsOpen}>
            <Card>
              <CollapsibleTrigger asChild>
                <CardHeader className="cursor-pointer hover-elevate" data-testid="collapsible-profile-guidance">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <Lightbulb className="h-5 w-5 text-primary" />
                      <CardTitle className="text-lg">Profile-Based Guidance</CardTitle>
                    </div>
                    {suggestionsOpen ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
                  </div>
                  <CardDescription>
                    Core recommendations based on your profile type
                  </CardDescription>
                </CardHeader>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <CardContent className="pt-0">
                  <div className="grid gap-4 md:grid-cols-3">
                    <div className="p-4 border rounded-lg">
                      <div className="flex items-center gap-2 mb-2">
                        <Zap className="h-4 w-4 text-orange-500" />
                        <h4 className="font-semibold text-sm">Immediate Actions</h4>
                      </div>
                      <p className="text-sm text-muted-foreground">{profile.suggestions.immediate}</p>
                    </div>
                    <div className="p-4 border rounded-lg">
                      <div className="flex items-center gap-2 mb-2">
                        <TrendingUp className="h-4 w-4 text-blue-500" />
                        <h4 className="font-semibold text-sm">Medium-term Goals</h4>
                      </div>
                      <p className="text-sm text-muted-foreground">{profile.suggestions.mediumTerm}</p>
                    </div>
                    <div className="p-4 border rounded-lg">
                      <div className="flex items-center gap-2 mb-2">
                        <Brain className="h-4 w-4 text-purple-500" />
                        <h4 className="font-semibold text-sm">Mindset Shifts</h4>
                      </div>
                      <p className="text-sm text-muted-foreground">{profile.suggestions.mindset}</p>
                    </div>
                  </div>
                </CardContent>
              </CollapsibleContent>
            </Card>
          </Collapsible>

          {/* Philosophical Narrative */}
          <Collapsible open={narrativeOpen} onOpenChange={setNarrativeOpen}>
            <Card>
              <CollapsibleTrigger asChild>
                <CardHeader className="cursor-pointer hover-elevate" data-testid="collapsible-story-philosophy">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <Heart className="h-5 w-5 text-primary" />
                      <CardTitle className="text-lg">Your Story & Philosophy</CardTitle>
                    </div>
                    {narrativeOpen ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
                  </div>
                  <CardDescription>
                    Deeper insights into your profile and life philosophy
                  </CardDescription>
                </CardHeader>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <CardContent className="pt-0">
                  <div className="space-y-4">
                    <div className="p-4 bg-accent/10 rounded-lg border border-accent/20">
                      <h4 className="font-semibold mb-2">Life Philosophy</h4>
                      <p className="text-muted-foreground italic">"{profile.philosophy}"</p>
                    </div>
                    <div>
                      <h4 className="font-semibold mb-2">Who Else Went Through This</h4>
                      <p className="text-muted-foreground">{profile.whoElseWentThroughThis}</p>
                    </div>
                    <div>
                      <h4 className="font-semibold mb-2 flex items-center gap-2">
                        <Star className="h-4 w-4 text-yellow-500" />
                        Celebrity Parallel
                      </h4>
                      <p className="text-muted-foreground">{profile.celebrityParallel}</p>
                    </div>
                  </div>
                </CardContent>
              </CollapsibleContent>
            </Card>
          </Collapsible>

          {/* Risk Analytics */}
          {eriResults && (
            <Collapsible open={analyticsOpen} onOpenChange={setAnalyticsOpen}>
              <Card>
                <CollapsibleTrigger asChild>
                  <CardHeader className="cursor-pointer hover-elevate" data-testid="collapsible-risk-analysis">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <BarChart3 className="h-5 w-5 text-primary" />
                        <CardTitle className="text-lg">Risk Analysis</CardTitle>
                      </div>
                      {analyticsOpen ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
                    </div>
                    <CardDescription>
                      Detailed breakdown of your emotional risk factors
                    </CardDescription>
                  </CardHeader>
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <CardContent className="pt-0">
                    {/* Risk Radar Chart */}
                    <div className="mb-8">
                      <RiskRadarChart 
                        eriResults={eriResults}
                        onRetakeAssessment={onStartOver}
                      />
                    </div>

                    {/* ERI Score Summary */}
                    <div className="grid gap-4 md:grid-cols-2">
                      <div className="p-4 border rounded-lg">
                        <h4 className="font-semibold mb-3 flex items-center gap-2">
                          <Activity className="h-4 w-4 text-blue-500" />
                          ERI Score Breakdown
                        </h4>
                        <div className="space-y-2">
                          <div className="flex justify-between text-sm">
                            <span>Overall Score:</span>
                            <span className="font-medium">{eriResults.eriScore}/100</span>
                          </div>
                          <div className="flex justify-between text-sm">
                            <span>Risk Level:</span>
                            <Badge variant={eriResults.riskLevel === 'Low' ? 'default' : eriResults.riskLevel === 'Medium' ? 'secondary' : 'destructive'} className="text-xs">
                              {eriResults.riskLevel}
                            </Badge>
                          </div>
                        </div>
                      </div>
                      <div className="p-4 border rounded-lg">
                        <h4 className="font-semibold mb-3">Risk Factors</h4>
                        <div className="space-y-2 text-sm">
                          {Object.entries(eriResults.subScores).map(([key, value]) => (
                            <div key={key} className="flex justify-between">
                              <span className="capitalize">{key.replace('_', ' ')}:</span>
                              <span className="font-medium">{Math.round((value as number) * 100)}/100</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </CollapsibleContent>
              </Card>
            </Collapsible>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap justify-center gap-4 mt-8">
          <Button 
            variant="outline" 
            onClick={onStartOver}
            className="hover-elevate"
            data-testid="button-start-over"
          >
            <ChevronLeft className="h-4 w-4 mr-2" />
            Take Assessment Again
          </Button>
          
          <Button 
            variant="outline" 
            onClick={handleExport}
            className="hover-elevate"
            data-testid="button-export-results"
          >
            <Download className="h-4 w-4 mr-2" />
            Export Results
          </Button>
          
          <Button 
            variant="outline" 
            onClick={handleShare}
            className="hover-elevate"
            data-testid="button-share-results"
          >
            <Share2 className="h-4 w-4 mr-2" />
            Share Profile
          </Button>
        </div>

        {/* Disclaimer */}
        <Card className="mt-12 bg-card/50 border-primary/20">
          <CardContent className="pt-6">
            <p className="text-sm text-muted-foreground text-center">
              <strong>Important:</strong> This assessment is for informational purposes only and 
              should not replace professional mental health care. If you're experiencing severe 
              symptoms, please consult with a qualified healthcare provider.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}