import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ChevronLeft, Download, Share2, Lightbulb, Heart, TrendingUp, Zap, Target, Brain, ExternalLink, AlertTriangle } from "lucide-react";
import { RiskProfile } from "@shared/schema";
import { ProfileCard } from "./ProfileCard";
import type { PersonalizedRecommendations } from "../utils/adaptiveSuggestions";

interface ResultsPageProps {
  profile: RiskProfile;
  adaptiveRecommendations: PersonalizedRecommendations | null;
  eriResults: { eriScore: number; riskLevel: string; subScores: any } | null;
  onStartOver: () => void;
}

export function ResultsPage({ profile, adaptiveRecommendations, eriResults, onStartOver }: ResultsPageProps) {
  const [showDetails, setShowDetails] = useState(false);

  const handleExport = () => {
    // Create a simple text export of the results
    const results = `
Mental Health Risk Profile Results
=================================

Profile: ${profile.name} ${profile.emoji}

Emotional Narrative:
"${profile.narrative}"

Key Philosophy:
"${profile.philosophy}"

Detailed Profile:
${profile.narrative}

Recommended Actions:
Immediate: ${profile.suggestions.immediate}
Medium-term: ${profile.suggestions.mediumTerm}
Mindset: ${profile.suggestions.mindset}

Who Else Went Through This:
${profile.whoElseWentThroughThis}

Celebrity Parallel: ${profile.celebrityParallel}

---
This assessment is for informational purposes only and should not replace professional mental health care.
Generated by Mental Health Risk Profiling Tool
    `.trim();

    const blob = new Blob([results], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mental-health-profile-${profile.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: 'Mental Health Risk Profile',
        text: `I completed a mental health assessment and my profile is: ${profile.name}`,
        url: window.location.href
      });
    } else {
      // Fallback to clipboard
      navigator.clipboard.writeText(
        `I completed a mental health assessment and my profile is: ${profile.name} - ${window.location.href}`
      );
      console.log('Results copied to clipboard');
    }
  };

  if (!showDetails) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-primary/5 to-accent/10 p-4">
        <div className="container mx-auto max-w-4xl py-8">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold mb-2">Your Mental Health Profile</h1>
            <p className="text-muted-foreground">
              Based on your responses, here's your personalized risk profile and recommendations
            </p>
          </div>

          {/* Profile Card */}
          <ProfileCard 
            profile={profile}
            onViewDetails={() => setShowDetails(true)}
          />

          {/* Action Buttons */}
          <div className="flex flex-wrap justify-center gap-4 mt-8">
            <Button 
              variant="outline" 
              onClick={onStartOver}
              className="hover-elevate"
              data-testid="button-start-over"
            >
              <ChevronLeft className="h-4 w-4 mr-2" />
              Take Assessment Again
            </Button>
            
            <Button 
              variant="outline" 
              onClick={handleExport}
              className="hover-elevate"
              data-testid="button-export-results"
            >
              <Download className="h-4 w-4 mr-2" />
              Export Results
            </Button>
            
            <Button 
              variant="outline" 
              onClick={handleShare}
              className="hover-elevate"
              data-testid="button-share-results"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Share Profile
            </Button>
          </div>

          {/* Disclaimer */}
          <Card className="mt-12 bg-card/50 border-primary/20">
            <CardContent className="pt-6">
              <p className="text-sm text-muted-foreground text-center">
                <strong>Important:</strong> This assessment is for informational purposes only and 
                should not replace professional mental health care. If you're experiencing severe 
                symptoms, please consult with a qualified healthcare provider.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background p-4">
      <div className="container mx-auto max-w-4xl py-8">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Button 
            variant="ghost" 
            onClick={() => setShowDetails(false)}
            className="hover-elevate"
            data-testid="button-back-to-summary"
          >
            <ChevronLeft className="h-4 w-4 mr-2" />
            Back to Summary
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Detailed Profile Analysis</h1>
            <p className="text-muted-foreground">{profile.name} {profile.emoji}</p>
          </div>
        </div>

        <div className="grid gap-8">
          {/* Expanded Narrative */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Heart className="h-5 w-5 text-primary" />
                Understanding Your Profile
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-lg leading-relaxed">{profile.narrative}</p>
              
              <Separator className="my-6" />
              
              <div className="bg-primary/5 p-4 rounded-md border-l-4 border-primary">
                <p className="font-medium text-primary italic">"{profile.philosophy}"</p>
              </div>
            </CardContent>
          </Card>

          {/* Profile-Based Recommendations */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Heart className="h-5 w-5 text-primary" />
                Profile-Based Recommendations
              </CardTitle>
              <CardDescription>
                Core strategies based on your {profile.name} profile
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                  <div>
                    <p className="font-semibold text-sm mb-1">Immediate Action:</p>
                    <p>{profile.suggestions.immediate}</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                  <div>
                    <p className="font-semibold text-sm mb-1">Medium-term Goal:</p>
                    <p>{profile.suggestions.mediumTerm}</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                  <div>
                    <p className="font-semibold text-sm mb-1">Mindset Shift:</p>
                    <p>{profile.suggestions.mindset}</p>
                  </div>
                </div>
              </div>
              
              <Separator className="my-6" />
              
              <div className="bg-accent/20 p-4 rounded-md">
                <h4 className="font-semibold mb-2">Guiding Philosophy</h4>
                <p className="font-medium text-primary">"{profile.philosophy}"</p>
              </div>
            </CardContent>
          </Card>

          {/* Enhanced Adaptive Recommendations */}
          {adaptiveRecommendations && (
            <Card className="border-orange-200 dark:border-orange-800">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Zap className="h-5 w-5 text-orange-600" />
                  Personalized Action Plan
                  {eriResults && (
                    <Badge variant="outline" className="ml-2">
                      ERI Score: {eriResults.eriScore}/100
                    </Badge>
                  )}
                </CardTitle>
                <CardDescription>
                  {adaptiveRecommendations.contextualMessage}
                </CardDescription>
              </CardHeader>
              <CardContent>
                {/* Primary Adaptive Suggestions */}
                <div className="space-y-6">
                  {adaptiveRecommendations.primarySuggestions.map((suggestion, index) => {
                    const IconComponent = suggestion.category === "immediate" ? Zap : 
                                         suggestion.category === "mediumTerm" ? Target : 
                                         suggestion.category === "mindset" ? Brain : 
                                         Lightbulb;
                    
                    return (
                      <div key={index} className="border rounded-lg p-4 bg-gradient-to-r from-orange-50/50 to-transparent dark:from-orange-950/20">
                        <div className="flex items-start gap-3">
                          <IconComponent className="h-5 w-5 text-orange-600 mt-1 flex-shrink-0" />
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              <Badge variant="secondary" className="text-xs">
                                {suggestion.category === "immediate" ? "Act Now" : 
                                 suggestion.category === "mediumTerm" ? "Build Over Time" : 
                                 suggestion.category === "mindset" ? "Mindset Shift" : 
                                 "Resources"}
                              </Badge>
                              <span className="text-xs text-muted-foreground">
                                Priority: {suggestion.priority}/5
                              </span>
                            </div>
                            <p className="font-medium mb-2">{suggestion.text}</p>
                            <p className="text-sm text-muted-foreground mb-3">{suggestion.reasoning}</p>
                            
                            {/* Suggestion Resources */}
                            {suggestion.resources.length > 0 && (
                              <div className="space-y-2">
                                <p className="text-xs font-semibold text-muted-foreground">Recommended Tools:</p>
                                <div className="flex flex-wrap gap-2">
                                  {suggestion.resources.slice(0, 2).map((resource) => (
                                    <Badge key={resource.id} variant="outline" className="text-xs">
                                      {resource.title}
                                    </Badge>
                                  ))}
                                </div>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>

                <Separator className="my-6" />

                {/* Additional Resources */}
                {adaptiveRecommendations.additionalResources.length > 0 && (
                  <div>
                    <h4 className="font-semibold mb-3 flex items-center gap-2">
                      <ExternalLink className="h-4 w-4" />
                      Recommended Resources
                    </h4>
                    <div className="grid gap-3 md:grid-cols-2">
                      {adaptiveRecommendations.additionalResources.slice(0, 4).map((resource) => (
                        <div key={resource.id} className="border rounded p-3 hover-elevate">
                          <div className="flex items-start justify-between gap-2">
                            <div>
                              <p className="font-medium text-sm">{resource.title}</p>
                              <p className="text-xs text-muted-foreground mb-2">{resource.description}</p>
                              <Badge variant="outline" className="text-xs">
                                {resource.type}
                              </Badge>
                            </div>
                            {resource.url && (
                              <ExternalLink className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Emergency Support */}
                {adaptiveRecommendations.emergencySupport.length > 0 && (
                  <div className="mt-6 p-4 bg-red-50 dark:bg-red-950/20 border border-red-200 dark:border-red-800 rounded-lg">
                    <div className="flex items-center gap-2 mb-3">
                      <AlertTriangle className="h-5 w-5 text-red-600" />
                      <h4 className="font-semibold text-red-900 dark:text-red-100">Crisis Support Available</h4>
                    </div>
                    <div className="space-y-2">
                      {adaptiveRecommendations.emergencySupport.map((support) => (
                        <div key={support.id} className="flex items-center justify-between">
                          <div>
                            <p className="font-medium text-sm text-red-900 dark:text-red-100">{support.title}</p>
                            <p className="text-xs text-red-700 dark:text-red-300">{support.description}</p>
                          </div>
                          {support.url && (
                            <ExternalLink className="h-4 w-4 text-red-600 flex-shrink-0" />
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Support & Statistics */}
          <div className="grid md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5 text-primary" />
                  Who Else Went Through This?
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm">{profile.whoElseWentThroughThis}</p>
                
                <Separator className="my-4" />
                
                <div>
                  <p className="text-sm text-muted-foreground mb-2">Similar journey:</p>
                  <p className="text-sm">{profile.celebrityParallel}</p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Profile Characteristics</CardTitle>
                <CardDescription>Key factors that define your profile</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <Badge variant="outline" className="mr-2 mb-2">
                    {profile.criteria.occupation}
                  </Badge>
                  <Badge variant="outline" className="mr-2 mb-2">
                    Stress Level: {profile.criteria.stress}
                  </Badge>
                  <Badge variant="outline" className="mr-2 mb-2">
                    Interview Comfort: {profile.criteria.interview_comfort}
                  </Badge>
                  <Badge variant="outline" className="mr-2 mb-2">
                    Treatment History: {profile.criteria.treatment}
                  </Badge>
                  <Badge variant="outline" className="mr-2 mb-2">
                    Mood Swings: {profile.criteria.mood_swings}
                  </Badge>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap justify-center gap-4">
            <Button 
              onClick={onStartOver}
              className="hover-elevate"
              data-testid="button-start-over-detailed"
            >
              Take Assessment Again
            </Button>
            
            <Button 
              variant="outline" 
              onClick={handleExport}
              className="hover-elevate"
              data-testid="button-export-detailed"
            >
              <Download className="h-4 w-4 mr-2" />
              Export Full Report
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}