import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ChevronLeft, Download, Share2, Lightbulb, Heart, TrendingUp } from "lucide-react";
import { RiskProfile } from "@shared/schema";
import { ProfileCard } from "./ProfileCard";

interface ResultsPageProps {
  profile: RiskProfile;
  onStartOver: () => void;
}

export function ResultsPage({ profile, onStartOver }: ResultsPageProps) {
  const [showDetails, setShowDetails] = useState(false);

  const handleExport = () => {
    // Create a simple text export of the results
    const results = `
Mental Health Risk Profile Results
=================================

Profile: ${profile.name} ${profile.emoji}

Emotional Narrative:
"${profile.emotionalNarrative}"

Key Philosophy:
"${profile.quote}"

Detailed Profile:
${profile.expandedNarrative}

Recommended Actions:
${profile.suggestions.map(s => `• ${s}`).join('\n')}

You're Not Alone:
${profile.youreNotAlone}

Celebrity Parallel: ${profile.celebrityParallel}

---
This assessment is for informational purposes only and should not replace professional mental health care.
Generated by Mental Health Risk Profiling Tool
    `.trim();

    const blob = new Blob([results], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mental-health-profile-${profile.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: 'Mental Health Risk Profile',
        text: `I completed a mental health assessment and my profile is: ${profile.name}`,
        url: window.location.href
      });
    } else {
      // Fallback to clipboard
      navigator.clipboard.writeText(
        `I completed a mental health assessment and my profile is: ${profile.name} - ${window.location.href}`
      );
      console.log('Results copied to clipboard');
    }
  };

  if (!showDetails) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-primary/5 to-accent/10 p-4">
        <div className="container mx-auto max-w-4xl py-8">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold mb-2">Your Mental Health Profile</h1>
            <p className="text-muted-foreground">
              Based on your responses, here's your personalized risk profile and recommendations
            </p>
          </div>

          {/* Profile Card */}
          <ProfileCard 
            profile={profile}
            onViewDetails={() => setShowDetails(true)}
          />

          {/* Action Buttons */}
          <div className="flex flex-wrap justify-center gap-4 mt-8">
            <Button 
              variant="outline" 
              onClick={onStartOver}
              className="hover-elevate"
              data-testid="button-start-over"
            >
              <ChevronLeft className="h-4 w-4 mr-2" />
              Take Assessment Again
            </Button>
            
            <Button 
              variant="outline" 
              onClick={handleExport}
              className="hover-elevate"
              data-testid="button-export-results"
            >
              <Download className="h-4 w-4 mr-2" />
              Export Results
            </Button>
            
            <Button 
              variant="outline" 
              onClick={handleShare}
              className="hover-elevate"
              data-testid="button-share-results"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Share Profile
            </Button>
          </div>

          {/* Disclaimer */}
          <Card className="mt-12 bg-card/50 border-primary/20">
            <CardContent className="pt-6">
              <p className="text-sm text-muted-foreground text-center">
                <strong>Important:</strong> This assessment is for informational purposes only and 
                should not replace professional mental health care. If you're experiencing severe 
                symptoms, please consult with a qualified healthcare provider.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background p-4">
      <div className="container mx-auto max-w-4xl py-8">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Button 
            variant="ghost" 
            onClick={() => setShowDetails(false)}
            className="hover-elevate"
            data-testid="button-back-to-summary"
          >
            <ChevronLeft className="h-4 w-4 mr-2" />
            Back to Summary
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Detailed Profile Analysis</h1>
            <p className="text-muted-foreground">{profile.name} {profile.emoji}</p>
          </div>
        </div>

        <div className="grid gap-8">
          {/* Expanded Narrative */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Heart className="h-5 w-5 text-primary" />
                Understanding Your Profile
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-lg leading-relaxed">{profile.expandedNarrative}</p>
              
              <Separator className="my-6" />
              
              <div className="bg-primary/5 p-4 rounded-md border-l-4 border-primary">
                <p className="font-medium text-primary italic">"{profile.emotionalNarrative}"</p>
              </div>
            </CardContent>
          </Card>

          {/* Recommendations */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lightbulb className="h-5 w-5 text-primary" />
                Personalized Recommendations
              </CardTitle>
              <CardDescription>
                Evidence-based strategies tailored to your profile
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {profile.suggestions.map((suggestion, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0"></div>
                    <p>{suggestion}</p>
                  </div>
                ))}
              </div>
              
              <Separator className="my-6" />
              
              <div className="bg-accent/20 p-4 rounded-md">
                <h4 className="font-semibold mb-2">Guiding Philosophy</h4>
                <p className="font-medium text-primary">"{profile.quote}"</p>
              </div>
            </CardContent>
          </Card>

          {/* Support & Statistics */}
          <div className="grid md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5 text-primary" />
                  You're Not Alone
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm">{profile.youreNotAlone}</p>
                
                <Separator className="my-4" />
                
                <div>
                  <p className="text-sm text-muted-foreground mb-2">Similar journey as:</p>
                  <Badge variant="secondary" className="text-sm">
                    {profile.celebrityParallel}
                  </Badge>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Key Indicators</CardTitle>
                <CardDescription>Factors that influenced your profile</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {profile.keySignals.map((signal, index) => (
                    <Badge key={index} variant="outline" className="mr-2 mb-2">
                      {signal}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap justify-center gap-4">
            <Button 
              onClick={onStartOver}
              className="hover-elevate"
              data-testid="button-start-over-detailed"
            >
              Take Assessment Again
            </Button>
            
            <Button 
              variant="outline" 
              onClick={handleExport}
              className="hover-elevate"
              data-testid="button-export-detailed"
            >
              <Download className="h-4 w-4 mr-2" />
              Export Full Report
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}